// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum ObjectType : int {
  OBJECT_TYPE_NONE = 0,
  OBJECT_TYPE_CREATURE = 1,
  OBJECT_TYPE_PROJECTILE = 2,
  OBJECT_TYPE_ENV = 3,
  ObjectType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ObjectType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ObjectType_IsValid(int value);
constexpr ObjectType ObjectType_MIN = OBJECT_TYPE_NONE;
constexpr ObjectType ObjectType_MAX = OBJECT_TYPE_ENV;
constexpr int ObjectType_ARRAYSIZE = ObjectType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ObjectType_descriptor();
template<typename T>
inline const std::string& ObjectType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ObjectType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ObjectType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ObjectType_descriptor(), enum_t_value);
}
inline bool ObjectType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ObjectType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ObjectType>(
    ObjectType_descriptor(), name, value);
}
enum CharacterClass : int {
  CLASS_TYPE_NONE = 0,
  CLASS_TYPE_WARRIOR = 1,
  CLASS_TYPE_MAGE = 2,
  CharacterClass_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  CharacterClass_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool CharacterClass_IsValid(int value);
constexpr CharacterClass CharacterClass_MIN = CLASS_TYPE_NONE;
constexpr CharacterClass CharacterClass_MAX = CLASS_TYPE_MAGE;
constexpr int CharacterClass_ARRAYSIZE = CharacterClass_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CharacterClass_descriptor();
template<typename T>
inline const std::string& CharacterClass_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CharacterClass>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CharacterClass_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CharacterClass_descriptor(), enum_t_value);
}
inline bool CharacterClass_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CharacterClass* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CharacterClass>(
    CharacterClass_descriptor(), name, value);
}
enum MoveState : int {
  MOVE_STATE_NONE = 0,
  MOVE_STATE_IDLE = 1,
  MOVE_STATE_RUN = 2,
  MOVE_STATE_JUMP = 3,
  MoveState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MoveState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MoveState_IsValid(int value);
constexpr MoveState MoveState_MIN = MOVE_STATE_NONE;
constexpr MoveState MoveState_MAX = MOVE_STATE_JUMP;
constexpr int MoveState_ARRAYSIZE = MoveState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MoveState_descriptor();
template<typename T>
inline const std::string& MoveState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MoveState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MoveState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MoveState_descriptor(), enum_t_value);
}
inline bool MoveState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MoveState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MoveState>(
    MoveState_descriptor(), name, value);
}
enum HitType : int {
  HIT_TYPE_NONE = 0,
  HIT_TYPE_NORMAL = 1,
  HIT_TYPE_SKILL = 2,
  HIT_TYPE_EOT = 3,
  HitType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  HitType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool HitType_IsValid(int value);
constexpr HitType HitType_MIN = HIT_TYPE_NONE;
constexpr HitType HitType_MAX = HIT_TYPE_EOT;
constexpr int HitType_ARRAYSIZE = HitType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* HitType_descriptor();
template<typename T>
inline const std::string& HitType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, HitType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function HitType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    HitType_descriptor(), enum_t_value);
}
inline bool HitType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, HitType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<HitType>(
    HitType_descriptor(), name, value);
}
enum DamageType : int {
  DAMAGE_TYPE_NONE = 0,
  DAMAGE_TYPE_PHYSICAL = 1,
  DAMAGE_TYPE_MAGICAL = 2,
  DAMAGE_TYPE_BURN = 3,
  DAMAGE_TYPE_POSION = 4,
  DamageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DamageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DamageType_IsValid(int value);
constexpr DamageType DamageType_MIN = DAMAGE_TYPE_NONE;
constexpr DamageType DamageType_MAX = DAMAGE_TYPE_POSION;
constexpr int DamageType_ARRAYSIZE = DamageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DamageType_descriptor();
template<typename T>
inline const std::string& DamageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DamageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DamageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DamageType_descriptor(), enum_t_value);
}
inline bool DamageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DamageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DamageType>(
    DamageType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::ObjectType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ObjectType>() {
  return ::Protocol::ObjectType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::CharacterClass> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::CharacterClass>() {
  return ::Protocol::CharacterClass_descriptor();
}
template <> struct is_proto_enum< ::Protocol::MoveState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::MoveState>() {
  return ::Protocol::MoveState_descriptor();
}
template <> struct is_proto_enum< ::Protocol::HitType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::HitType>() {
  return ::Protocol::HitType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::DamageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::DamageType>() {
  return ::Protocol::DamageType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
