// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#include "Enum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
}  // namespace Protocol
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Enum_2eproto[14];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Enum_2eproto = nullptr;
const uint32_t TableStruct_Enum_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Enum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nEnum.proto\022\010Protocol*\204\001\n\nObjectType\022\024\n"
  "\020OBJECT_TYPE_NONE\020\000\022\026\n\022OBJECT_TYPE_PLAYE"
  "R\020\001\022\027\n\023OBJECT_TYPE_MONSTER\020\002\022\032\n\026OBJECT_T"
  "YPE_PROJECTILE\020\003\022\023\n\017OBJECT_TYPE_ENV\020\004*R\n"
  "\016CharacterClass\022\023\n\017CLASS_TYPE_NONE\020\000\022\026\n\022"
  "CLASS_TYPE_WARRIOR\020\001\022\023\n\017CLASS_TYPE_MAGE\020"
  "\002*`\n\tMoveState\022\023\n\017MOVE_STATE_NONE\020\000\022\023\n\017M"
  "OVE_STATE_IDLE\020\001\022\022\n\016MOVE_STATE_RUN\020\002\022\025\n\021"
  "MOVE_STATE_ACTION\020\003*W\n\007HitType\022\021\n\rHIT_TY"
  "PE_NONE\020\000\022\023\n\017HIT_TYPE_NORMAL\020\001\022\022\n\016HIT_TY"
  "PE_SKILL\020\002\022\020\n\014HIT_TYPE_EOT\020\003*j\n\nDamageTy"
  "pe\022\024\n\020DAMAGE_TYPE_NONE\020\000\022\030\n\024DAMAGE_TYPE_"
  "PHYSICAL\020\001\022\027\n\023DAMAGE_TYPE_MAGICAL\020\002\022\023\n\017D"
  "AMAGE_TYPE_FIX\020\003*\240\001\n\nEffectType\022\024\n\020EFFEC"
  "T_TYPE_NONE\020\000\022\030\n\024EFFECT_TYPE_BLEEDING\020\001\022"
  "\024\n\020EFFECT_TYPE_BURN\020\002\022\026\n\022EFFECT_TYPE_POS"
  "ION\020\003\022\030\n\024EFFECT_TYPE_SPEED_UP\020\004\022\032\n\026EFFEC"
  "T_TYPE_SPEED_DOWN\020\005*i\n\010ItemType\022\022\n\016ITEM_"
  "TYPE_NONE\020\000\022\022\n\016ITEM_TYPE_GEAR\020\001\022\030\n\024ITEM_"
  "TYPE_CONSUMABLE\020\002\022\033\n\027ITEM_TYPE_MISCELLAN"
  "EOUS\020\003*\253\001\n\010SlotType\022\022\n\016SLOT_TYPE_NONE\020\000\022"
  "\034\n\030SLOT_TYPE_INVENTORY_GEAR\020\001\022\"\n\036SLOT_TY"
  "PE_INVENTORY_CONSUMABLE\020\002\022\034\n\030SLOT_TYPE_I"
  "NVENTORY_MISC\020\003\022\026\n\022SLOT_TYPE_EQUIPPED\020\004\022"
  "\023\n\017SLOT_TYPE_QUICK\020\005*\276\001\n\010StatType\022\022\n\016STA"
  "T_TYPE_NONE\020\000\022\024\n\020STAT_TYPE_MAX_HP\020\001\022\020\n\014S"
  "TAT_TYPE_HP\020\002\022\024\n\020STAT_TYPE_MAX_MP\020\003\022\020\n\014S"
  "TAT_TYPE_MP\020\004\022\035\n\031STAT_TYPE_PHYSICAL_ATTA"
  "CK\020\005\022\034\n\030STAT_TYPE_MAGICAL_ATTACK\020\006\022\021\n\rST"
  "AT_TYPE_EXP\020\007*q\n\013UpdateState\022\025\n\021UPDATE_S"
  "TATE_NONE\020\000\022\026\n\022UPDATE_STATE_ADDED\020\001\022\031\n\025U"
  "PDATE_STATE_MODIFIED\020\002\022\030\n\024UPDATE_STATE_R"
  "EMOVED\020\003*\234\001\n\010GearType\022\022\n\016GEAR_TYPE_NONE\020"
  "\000\022\024\n\020GEAR_TYPE_HELMET\020\001\022\023\n\017GEAR_TYPE_CHE"
  "ST\020\002\022\022\n\016GEAR_TYPE_LEGS\020\003\022\022\n\016GEAR_TYPE_AR"
  "MS\020\004\022\023\n\017GEAR_TYPE_BOOTS\020\005\022\024\n\020GEAR_TYPE_W"
  "EAPON\020\006*\225\002\n\013RespawnType\022\025\n\021RESPAWN_TYPE_"
  "NONE\020\000\022\025\n\021RESPAWN_TYPE_TOWN\020\001\022\033\n\027RESPAWN"
  "_TYPE_CHECKPOINT\020\002\022\"\n\036RESPAWN_TYPE_RESUR"
  "RECTION_ITEM\020\003\022\031\n\025RESPAWN_TYPE_IN_PLACE\020"
  "\004\022\035\n\031RESPAWN_TYPE_PARTY_MEMBER\020\005\022\033\n\027RESP"
  "AWN_TYPE_GUILD_BASE\020\006\022\032\n\026RESPAWN_TYPE_CA"
  "SH_ITEM\020\007\022$\n RESPAWN_TYPE_BATTLE_RESURRE"
  "CTION\020\010*\276\001\n\016TeleportReason\022\030\n\024TELEPORT_R"
  "EASON_NONE\020\000\022#\n\037TELEPORT_REASON_RETURN_B"
  "Y_DEATH\020\001\022$\n TELEPORT_REASON_TELEPORT_BY"
  "_ITEM\020\002\022\"\n\036TELEPORT_REASON_ENTER_BY_QUES"
  "T\020\003\022#\n\037TELEPORT_REASON_RECALL_BY_PARTY\020\004"
  "*\232\001\n\rRoomEnterType\022\030\n\024ROOM_ENTER_TYPE_NO"
  "NE\020\000\022\036\n\032ROOM_ENTER_TYPE_ENTER_GAME\020\001\022%\n!"
  "ROOM_ENTER_TYPE_MOVE_WITHIN_FIELD\020\002\022(\n$R"
  "OOM_ENTER_TYPE_TELEPORTED_BY_SYSTEM\020\003b\006p"
  "roto3"
  ;
static ::_pbi::once_flag descriptor_table_Enum_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Enum_2eproto = {
    false, false, 2085, descriptor_table_protodef_Enum_2eproto,
    "Enum.proto",
    &descriptor_table_Enum_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_Enum_2eproto::offsets,
    nullptr, file_level_enum_descriptors_Enum_2eproto,
    file_level_service_descriptors_Enum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Enum_2eproto_getter() {
  return &descriptor_table_Enum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Enum_2eproto(&descriptor_table_Enum_2eproto);
namespace Protocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ObjectType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[0];
}
bool ObjectType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CharacterClass_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[1];
}
bool CharacterClass_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MoveState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[2];
}
bool MoveState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* HitType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[3];
}
bool HitType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DamageType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[4];
}
bool DamageType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EffectType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[5];
}
bool EffectType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ItemType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[6];
}
bool ItemType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SlotType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[7];
}
bool SlotType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* StatType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[8];
}
bool StatType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* UpdateState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[9];
}
bool UpdateState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GearType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[10];
}
bool GearType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RespawnType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[11];
}
bool RespawnType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TeleportReason_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[12];
}
bool TeleportReason_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RoomEnterType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[13];
}
bool RoomEnterType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
