// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum ObjectType : int {
  OBJECT_TYPE_NONE = 0,
  OBJECT_TYPE_PLAYER = 1,
  OBJECT_TYPE_MONSTER = 2,
  OBJECT_TYPE_PROJECTILE = 3,
  OBJECT_TYPE_ENV = 4,
  ObjectType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ObjectType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ObjectType_IsValid(int value);
constexpr ObjectType ObjectType_MIN = OBJECT_TYPE_NONE;
constexpr ObjectType ObjectType_MAX = OBJECT_TYPE_ENV;
constexpr int ObjectType_ARRAYSIZE = ObjectType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ObjectType_descriptor();
template<typename T>
inline const std::string& ObjectType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ObjectType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ObjectType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ObjectType_descriptor(), enum_t_value);
}
inline bool ObjectType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ObjectType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ObjectType>(
    ObjectType_descriptor(), name, value);
}
enum CharacterClass : int {
  CLASS_TYPE_NONE = 0,
  CLASS_TYPE_WARRIOR = 1,
  CLASS_TYPE_MAGE = 2,
  CharacterClass_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  CharacterClass_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool CharacterClass_IsValid(int value);
constexpr CharacterClass CharacterClass_MIN = CLASS_TYPE_NONE;
constexpr CharacterClass CharacterClass_MAX = CLASS_TYPE_MAGE;
constexpr int CharacterClass_ARRAYSIZE = CharacterClass_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CharacterClass_descriptor();
template<typename T>
inline const std::string& CharacterClass_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CharacterClass>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CharacterClass_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CharacterClass_descriptor(), enum_t_value);
}
inline bool CharacterClass_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CharacterClass* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CharacterClass>(
    CharacterClass_descriptor(), name, value);
}
enum MoveState : int {
  MOVE_STATE_NONE = 0,
  MOVE_STATE_IDLE = 1,
  MOVE_STATE_RUN = 2,
  MOVE_STATE_ACTION = 3,
  MoveState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MoveState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MoveState_IsValid(int value);
constexpr MoveState MoveState_MIN = MOVE_STATE_NONE;
constexpr MoveState MoveState_MAX = MOVE_STATE_ACTION;
constexpr int MoveState_ARRAYSIZE = MoveState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MoveState_descriptor();
template<typename T>
inline const std::string& MoveState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MoveState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MoveState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MoveState_descriptor(), enum_t_value);
}
inline bool MoveState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MoveState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MoveState>(
    MoveState_descriptor(), name, value);
}
enum HitType : int {
  HIT_TYPE_NONE = 0,
  HIT_TYPE_NORMAL = 1,
  HIT_TYPE_SKILL = 2,
  HIT_TYPE_EOT = 3,
  HitType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  HitType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool HitType_IsValid(int value);
constexpr HitType HitType_MIN = HIT_TYPE_NONE;
constexpr HitType HitType_MAX = HIT_TYPE_EOT;
constexpr int HitType_ARRAYSIZE = HitType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* HitType_descriptor();
template<typename T>
inline const std::string& HitType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, HitType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function HitType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    HitType_descriptor(), enum_t_value);
}
inline bool HitType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, HitType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<HitType>(
    HitType_descriptor(), name, value);
}
enum DamageType : int {
  DAMAGE_TYPE_NONE = 0,
  DAMAGE_TYPE_PHYSICAL = 1,
  DAMAGE_TYPE_MAGICAL = 2,
  DAMAGE_TYPE_FIX = 3,
  DamageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DamageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DamageType_IsValid(int value);
constexpr DamageType DamageType_MIN = DAMAGE_TYPE_NONE;
constexpr DamageType DamageType_MAX = DAMAGE_TYPE_FIX;
constexpr int DamageType_ARRAYSIZE = DamageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DamageType_descriptor();
template<typename T>
inline const std::string& DamageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DamageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DamageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DamageType_descriptor(), enum_t_value);
}
inline bool DamageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DamageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DamageType>(
    DamageType_descriptor(), name, value);
}
enum EffectType : int {
  EFFECT_TYPE_NONE = 0,
  EFFECT_TYPE_BLEEDING = 1,
  EFFECT_TYPE_BURN = 2,
  EFFECT_TYPE_POSION = 3,
  EFFECT_TYPE_SPEED_UP = 4,
  EFFECT_TYPE_SPEED_DOWN = 5,
  EffectType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  EffectType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool EffectType_IsValid(int value);
constexpr EffectType EffectType_MIN = EFFECT_TYPE_NONE;
constexpr EffectType EffectType_MAX = EFFECT_TYPE_SPEED_DOWN;
constexpr int EffectType_ARRAYSIZE = EffectType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EffectType_descriptor();
template<typename T>
inline const std::string& EffectType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EffectType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EffectType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EffectType_descriptor(), enum_t_value);
}
inline bool EffectType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EffectType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EffectType>(
    EffectType_descriptor(), name, value);
}
enum ItemType : int {
  ITEM_TYPE_NONE = 0,
  ITEM_TYPE_GEAR = 1,
  ITEM_TYPE_CONSUMABLE = 2,
  ITEM_TYPE_MISCELLANEOUS = 3,
  ItemType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ItemType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ItemType_IsValid(int value);
constexpr ItemType ItemType_MIN = ITEM_TYPE_NONE;
constexpr ItemType ItemType_MAX = ITEM_TYPE_MISCELLANEOUS;
constexpr int ItemType_ARRAYSIZE = ItemType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ItemType_descriptor();
template<typename T>
inline const std::string& ItemType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ItemType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ItemType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ItemType_descriptor(), enum_t_value);
}
inline bool ItemType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ItemType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ItemType>(
    ItemType_descriptor(), name, value);
}
enum SlotType : int {
  SLOT_TYPE_NONE = 0,
  SLOT_TYPE_INVENTORY_GEAR = 1,
  SLOT_TYPE_INVENTORY_CONSUMABLE = 2,
  SLOT_TYPE_INVENTORY_MISC = 3,
  SLOT_TYPE_EQUIPPED = 4,
  SLOT_TYPE_QUICK = 5,
  SlotType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  SlotType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool SlotType_IsValid(int value);
constexpr SlotType SlotType_MIN = SLOT_TYPE_NONE;
constexpr SlotType SlotType_MAX = SLOT_TYPE_QUICK;
constexpr int SlotType_ARRAYSIZE = SlotType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SlotType_descriptor();
template<typename T>
inline const std::string& SlotType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SlotType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SlotType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SlotType_descriptor(), enum_t_value);
}
inline bool SlotType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SlotType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SlotType>(
    SlotType_descriptor(), name, value);
}
enum StatType : int {
  STAT_TYPE_NONE = 0,
  STAT_TYPE_MAX_HP = 1,
  STAT_TYPE_HP = 2,
  STAT_TYPE_MAX_MP = 3,
  STAT_TYPE_MP = 4,
  STAT_TYPE_PHYSICAL_ATTACK = 5,
  STAT_TYPE_MAGICAL_ATTACK = 6,
  STAT_TYPE_EXP = 7,
  StatType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  StatType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool StatType_IsValid(int value);
constexpr StatType StatType_MIN = STAT_TYPE_NONE;
constexpr StatType StatType_MAX = STAT_TYPE_EXP;
constexpr int StatType_ARRAYSIZE = StatType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* StatType_descriptor();
template<typename T>
inline const std::string& StatType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, StatType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function StatType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    StatType_descriptor(), enum_t_value);
}
inline bool StatType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, StatType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<StatType>(
    StatType_descriptor(), name, value);
}
enum UpdateState : int {
  UPDATE_STATE_NONE = 0,
  UPDATE_STATE_ADDED = 1,
  UPDATE_STATE_MODIFIED = 2,
  UPDATE_STATE_REMOVED = 3,
  UpdateState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  UpdateState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool UpdateState_IsValid(int value);
constexpr UpdateState UpdateState_MIN = UPDATE_STATE_NONE;
constexpr UpdateState UpdateState_MAX = UPDATE_STATE_REMOVED;
constexpr int UpdateState_ARRAYSIZE = UpdateState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* UpdateState_descriptor();
template<typename T>
inline const std::string& UpdateState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, UpdateState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function UpdateState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    UpdateState_descriptor(), enum_t_value);
}
inline bool UpdateState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, UpdateState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<UpdateState>(
    UpdateState_descriptor(), name, value);
}
enum GearType : int {
  GEAR_TYPE_NONE = 0,
  GEAR_TYPE_HELMET = 1,
  GEAR_TYPE_CHEST = 2,
  GEAR_TYPE_LEGS = 3,
  GEAR_TYPE_ARMS = 4,
  GEAR_TYPE_BOOTS = 5,
  GEAR_TYPE_WEAPON = 6,
  GearType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  GearType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool GearType_IsValid(int value);
constexpr GearType GearType_MIN = GEAR_TYPE_NONE;
constexpr GearType GearType_MAX = GEAR_TYPE_WEAPON;
constexpr int GearType_ARRAYSIZE = GearType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GearType_descriptor();
template<typename T>
inline const std::string& GearType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GearType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GearType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GearType_descriptor(), enum_t_value);
}
inline bool GearType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GearType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GearType>(
    GearType_descriptor(), name, value);
}
enum RespawnType : int {
  RESPAWN_TYPE_NONE = 0,
  RESPAWN_TYPE_TOWN = 1,
  RESPAWN_TYPE_CHECKPOINT = 2,
  RESPAWN_TYPE_RESURRECTION_ITEM = 3,
  RESPAWN_TYPE_IN_PLACE = 4,
  RESPAWN_TYPE_PARTY_MEMBER = 5,
  RESPAWN_TYPE_GUILD_BASE = 6,
  RESPAWN_TYPE_CASH_ITEM = 7,
  RESPAWN_TYPE_BATTLE_RESURRECTION = 8,
  RespawnType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  RespawnType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool RespawnType_IsValid(int value);
constexpr RespawnType RespawnType_MIN = RESPAWN_TYPE_NONE;
constexpr RespawnType RespawnType_MAX = RESPAWN_TYPE_BATTLE_RESURRECTION;
constexpr int RespawnType_ARRAYSIZE = RespawnType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RespawnType_descriptor();
template<typename T>
inline const std::string& RespawnType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RespawnType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RespawnType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RespawnType_descriptor(), enum_t_value);
}
inline bool RespawnType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RespawnType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RespawnType>(
    RespawnType_descriptor(), name, value);
}
enum EnterType : int {
  ENTER_TYPE_NONE = 0,
  ENTER_TYPE_ENTER_GAME = 1,
  ENTER_TYPE_USE_PORTAL = 2,
  ENTER_TYPE_USE_ITEM = 4,
  ENTER_TYPE_QUEST = 5,
  ENTER_TYPE_RECALL_BY_PARTY = 6,
  EnterType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  EnterType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool EnterType_IsValid(int value);
constexpr EnterType EnterType_MIN = ENTER_TYPE_NONE;
constexpr EnterType EnterType_MAX = ENTER_TYPE_RECALL_BY_PARTY;
constexpr int EnterType_ARRAYSIZE = EnterType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EnterType_descriptor();
template<typename T>
inline const std::string& EnterType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, EnterType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function EnterType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    EnterType_descriptor(), enum_t_value);
}
inline bool EnterType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, EnterType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EnterType>(
    EnterType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::ObjectType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ObjectType>() {
  return ::Protocol::ObjectType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::CharacterClass> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::CharacterClass>() {
  return ::Protocol::CharacterClass_descriptor();
}
template <> struct is_proto_enum< ::Protocol::MoveState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::MoveState>() {
  return ::Protocol::MoveState_descriptor();
}
template <> struct is_proto_enum< ::Protocol::HitType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::HitType>() {
  return ::Protocol::HitType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::DamageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::DamageType>() {
  return ::Protocol::DamageType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::EffectType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::EffectType>() {
  return ::Protocol::EffectType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::ItemType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::ItemType>() {
  return ::Protocol::ItemType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::SlotType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::SlotType>() {
  return ::Protocol::SlotType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::StatType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::StatType>() {
  return ::Protocol::StatType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::UpdateState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::UpdateState>() {
  return ::Protocol::UpdateState_descriptor();
}
template <> struct is_proto_enum< ::Protocol::GearType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::GearType>() {
  return ::Protocol::GearType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::RespawnType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::RespawnType>() {
  return ::Protocol::RespawnType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::EnterType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::EnterType>() {
  return ::Protocol::EnterType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
