syntax = "proto3";
package Protocol;

import "Enum.proto";
import "Struct.proto";

message C_PING
{

}

message S_PONG
{

}

message C_LOGIN
{
    string access_token = 1;
}

message S_LOGIN
{
	bool success = 1;
	repeated CharacterOverview characters = 2; // 캐릭터 아이디 발급 전
}

message C_CREATE_CHARACTER
{
    CharacterOverview character = 1;
}

message S_CREATE_CHARACTER
{
    bool success = 1;
    string cause = 2;
    int64 character_id = 3;
}

message C_DELETE_CHARACTER
{
    int64 character_id = 1;
}

message S_DELETE_CHARACTER
{
    bool success = 1;
    int64 character_id = 2;
}

message C_ENTER_GAME
{
	int64 character_id = 1;
}

message S_ENTER_GAME
{
	bool success = 1;
	ObjectInfo player = 2;  

    // 캐릭터 개인 정보
    StatInfo stat_info = 3;         // 스텟 정보
    Possession possession = 4;      // 소유물
}

message C_LEAVE_GAME
{

}

message S_LEAVE_GAME
{

}

message C_ENTER_MAP
{
    // 이 패킷은 게임 입장 후에 사용한다.
    int32 map_id = 1;
    optional PosInfo info = 2;      // 서버 검증용

    oneof enter_data
    {
        int32 portal_id = 3;       // 사용한 포탈 id
        int32 room_id = 4;
    }
}

message S_ENTER_MAP
{
    bool success = 1;
    int32 map_id = 2;
    int32 room_id = 3;
}

message C_ENTER_ROOM
{
    EnterType enter_type = 1;

    // Room 입장에 필요한 추가 데이터
    oneof enter_data
    {
        int32 room_id = 2;
        int32 portal_id = 3;
    }
}

message S_ENTER_ROOM
{
    bool success = 1;
    EnterType enter_type = 2;   // 요청 확인용
    int32 room_id = 3;

    // 게임에 참여하지 않고 단순 입장만 하는 경우 고려해서 optional 추가
    optional PosInfo enter_pos = 4; 
}

message S_SPAWN
{
	repeated ObjectInfo objects = 1;
}

message S_DESPAWN
{
	repeated int64 object_ids = 1;
}

message C_MOVE
{
	PosInfo info = 1;
}

message S_MOVE
{
	repeated PosInfo info = 1;
}

message C_NORMAL_ATTACK
{
    int32 combo = 1;
}

message S_NORMAL_ATTACK
{
    int64 object_id = 1;
    int32 combo = 2;
    float yaw = 3;
}

message S_HIT
{
    int64 object_id = 1;
    optional int64 updated_hp = 2; 
}

message C_BUY_ITEM
{
    int32 template_id = 1;
    int32 count = 2;        // 현재 1로 고정(그래서 사용안함)
}

message S_BUY_ITEM
{
    bool success = 1;
    Slot updated_slot = 2;
    int64 gold = 3;
}

message C_SELL_ITEM
{ 
    Slot slot = 1;
    int32 count = 2;        // 현재 1로 고정(그래서 사용안함)
}

message S_SELL_ITEM
{
    bool success = 1;
    Slot updated_slot = 2;
    int64 gold = 3;
}

message C_EQUIP_GEAR
{
    Slot slot = 1;
}

message S_EQUIP_GEAR
{
    bool success = 1;
    int64 object_id = 2;
    
    // 장착 결과
    int32 slot_id = 3; 
    int32 template_id = 4;

    // 장착 결과(나에게만)
    repeated Slot updated_slots = 5;
    repeated Stat updated_stat = 6;     // 바뀐 스탯
}

message C_UNEQUIP_GEAR
{
    Slot slot = 1;
}

message S_UNEQUIP_GEAR
{
    bool success = 1;
    int64 object_id = 2;

    // 장착 결과
    int32 slot_id = 3; 
    int32 template_id = 4;

    // 탈착 결과(나에게만)
    repeated Slot updated_slots = 5;
    repeated Stat updated_stat = 6;     
}

message C_USE_ITEM
{
    Slot slot = 1;
}

message S_USE_ITEM
{
    bool success = 1;
    int64 object_id = 2;

    // 사용 결과
    repeated Slot updated_slots = 3;
    repeated Stat updated_stat = 4;     // 바뀐 스탯
}

message S_DIE
{
    int64 object_id = 1;
}

message S_REWARD_RESULT
{
    RewardType type = 1;
    Reward reward = 2;

    // 갱신된 데이터
    int64 updated_exp = 3;
    int64 updated_gold = 4;
    bool is_level_up = 5;
    LevelUpInfo level_up_details = 6;
}

message C_RESPAWN
{
    RespawnType respawn_type = 1;

    // 리스폰 타입에 따라 사용
    oneof respawn_data
    {
        int64 item_uid = 2;           
        int32 checkpoint_id = 3;     
        int64 target_player_id = 4;  
        int32 town_id = 5;           
    }
}

message S_RESPAWN
{
    // S_RESPAWN은 리스폰 요청의 결과만 알려주고 실제 스폰은 하지 않는다.
    bool success = 1;
    string error_message = 2;
    RespawnType respawn_type = 3;
    int64 object_id = 4;

    // 리스폰시 변경된 데이터
    int32 room_id = 5;
    PosInfo pos_info = 6;
    repeated Stat updated_stat = 7;
}