syntax = "proto3";
package Protocol;

import "Enum.proto";

message CharacterOverview
{
    int64 character_id = 1;
    CharacterClass class = 2;
    string name = 3;
    int32 level = 4;
    //map<int32, int32> equipped_gear_summary = 5;
}

message ObjectInfo
{
	int64 object_id = 1;
	ObjectType object_type = 2;
	PosInfo pos_info = 3;

    // ObjectType에 따른 정보
    oneof details
    {
        // oneof 그룹 내의 모든 필드는 기본적으로 optional 효과를 가짐
        PlayerInfo player_info = 4;
        MonsterInfo monster_info = 5;
    }
}

message PlayerInfo
{
    // 캐릭터 공개 정보
    int64 character_id = 1;
    CharacterClass class = 2;
    string name = 3;
    int32 level = 4;

    int32 map_id = 5;
    int32 room_id = 6;

    map<int32, int32> equipped_gear_summary = 7;   // <SlotId(or GearType), template_id>
}

message Possession
{
    int64 gold = 1;
    Inventory inventory = 2;
    map<int32, Slot> equipped_gear = 3; // <SlotId(or GearType), Slot>
}

message MonsterInfo
{
    int32 template_id = 1;
    int32 hp = 2;
}

message Vector
{
    float x = 1;
    float y = 2;
    float z = 3;
}

message PosInfo
{
	int64 object_id = 1;
	Vector pos = 2;
    float yaw = 3;
	Vector move_direction = 4;
	MoveState state = 5;
}

message HitData
{
    int64 attacker_id = 1;         // object_id
    int64 target_id = 2;           // object_id

    DamageType damage_type = 3;     // 물리 피해? 마법 피해?
    int64 damage = 4;
}

message StatInfo
{
    map<int32, int64> info = 1;   // <StatType, Value>
}

message StatList
{
    repeated Stat list = 1;
}

message Stat
{
    StatType type = 1;
    bool is_gauge = 2;
    int64 value = 3;
}

message Effect
{
    int32 effect_id = 1;
    float duration = 2;
}

message GearInfo
{
    int32 enhance_level = 1;
    int32 durability = 2;
    int32 additional_physical_attack = 3;  // 추가 물리 공격력
    int32 additional_magical_attack = 4;   // 추가 마법 공격력
}

message Item
{
    int32 template_id = 1;
    optional int64 item_uid = 2;
    optional int32 count = 3;

    // 아이템 인스턴스 데이터
    oneof instance_data{
        GearInfo gearInfo = 4;
    }
}

message Slot
{
    int32 slot_id = 1;                  // 서버에선 딱 한 번만 세팅 1
    SlotType type = 2;                  // 서버에선 딱 한 번만 세팅 2
    optional UpdateState state = 3;     // 슬롯 갱신 상태: 서버가 세팅하고 클라이언트는 사용
    optional Item item = 4;
}

message Inventory
{
    repeated Slot gear = 1;
    repeated Slot consumables = 2;
    repeated Slot miscellaneous = 3;
}

message LevelUpInfo
{
    int32 old_level = 1;
    int32 new_level = 2;

//    int32 earned_skill_points = 3;
//    int32 earned_stat_points = 4;

    int64 new_max_hp = 5;
    int64 new_max_mp = 6;
    int64 new_physical_attack = 7;
    int64 new_magical_attack = 8;
}

message DiePenaltyInfo
{
    int64 updated_exp = 1;
}