// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Struct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Struct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Struct_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Struct_2eproto;
namespace Protocol {
class CharacterOverview;
struct CharacterOverviewDefaultTypeInternal;
extern CharacterOverviewDefaultTypeInternal _CharacterOverview_default_instance_;
class Effect;
struct EffectDefaultTypeInternal;
extern EffectDefaultTypeInternal _Effect_default_instance_;
class Equipment;
struct EquipmentDefaultTypeInternal;
extern EquipmentDefaultTypeInternal _Equipment_default_instance_;
class Item;
struct ItemDefaultTypeInternal;
extern ItemDefaultTypeInternal _Item_default_instance_;
class ObjectInfo;
struct ObjectInfoDefaultTypeInternal;
extern ObjectInfoDefaultTypeInternal _ObjectInfo_default_instance_;
class PlayerInfo;
struct PlayerInfoDefaultTypeInternal;
extern PlayerInfoDefaultTypeInternal _PlayerInfo_default_instance_;
class PosInfo;
struct PosInfoDefaultTypeInternal;
extern PosInfoDefaultTypeInternal _PosInfo_default_instance_;
class StatInfo;
struct StatInfoDefaultTypeInternal;
extern StatInfoDefaultTypeInternal _StatInfo_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::CharacterOverview* Arena::CreateMaybeMessage<::Protocol::CharacterOverview>(Arena*);
template<> ::Protocol::Effect* Arena::CreateMaybeMessage<::Protocol::Effect>(Arena*);
template<> ::Protocol::Equipment* Arena::CreateMaybeMessage<::Protocol::Equipment>(Arena*);
template<> ::Protocol::Item* Arena::CreateMaybeMessage<::Protocol::Item>(Arena*);
template<> ::Protocol::ObjectInfo* Arena::CreateMaybeMessage<::Protocol::ObjectInfo>(Arena*);
template<> ::Protocol::PlayerInfo* Arena::CreateMaybeMessage<::Protocol::PlayerInfo>(Arena*);
template<> ::Protocol::PosInfo* Arena::CreateMaybeMessage<::Protocol::PosInfo>(Arena*);
template<> ::Protocol::StatInfo* Arena::CreateMaybeMessage<::Protocol::StatInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class CharacterOverview final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.CharacterOverview) */ {
 public:
  inline CharacterOverview() : CharacterOverview(nullptr) {}
  ~CharacterOverview() override;
  explicit PROTOBUF_CONSTEXPR CharacterOverview(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CharacterOverview(const CharacterOverview& from);
  CharacterOverview(CharacterOverview&& from) noexcept
    : CharacterOverview() {
    *this = ::std::move(from);
  }

  inline CharacterOverview& operator=(const CharacterOverview& from) {
    CopyFrom(from);
    return *this;
  }
  inline CharacterOverview& operator=(CharacterOverview&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CharacterOverview& default_instance() {
    return *internal_default_instance();
  }
  static inline const CharacterOverview* internal_default_instance() {
    return reinterpret_cast<const CharacterOverview*>(
               &_CharacterOverview_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CharacterOverview& a, CharacterOverview& b) {
    a.Swap(&b);
  }
  inline void Swap(CharacterOverview* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CharacterOverview* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CharacterOverview* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CharacterOverview>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CharacterOverview& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CharacterOverview& from) {
    CharacterOverview::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CharacterOverview* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.CharacterOverview";
  }
  protected:
  explicit CharacterOverview(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 3,
    kCharacterIdFieldNumber = 1,
    kClassFieldNumber = 2,
    kLevelFieldNumber = 4,
  };
  // string name = 3;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // uint64 character_id = 1;
  void clear_character_id();
  uint64_t character_id() const;
  void set_character_id(uint64_t value);
  private:
  uint64_t _internal_character_id() const;
  void _internal_set_character_id(uint64_t value);
  public:

  // .Protocol.CharacterClass class = 2;
  void clear_class_();
  ::Protocol::CharacterClass class_() const;
  void set_class_(::Protocol::CharacterClass value);
  private:
  ::Protocol::CharacterClass _internal_class_() const;
  void _internal_set_class_(::Protocol::CharacterClass value);
  public:

  // uint32 level = 4;
  void clear_level();
  uint32_t level() const;
  void set_level(uint32_t value);
  private:
  uint32_t _internal_level() const;
  void _internal_set_level(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.CharacterOverview)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    uint64_t character_id_;
    int class__;
    uint32_t level_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class ObjectInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ObjectInfo) */ {
 public:
  inline ObjectInfo() : ObjectInfo(nullptr) {}
  ~ObjectInfo() override;
  explicit PROTOBUF_CONSTEXPR ObjectInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ObjectInfo(const ObjectInfo& from);
  ObjectInfo(ObjectInfo&& from) noexcept
    : ObjectInfo() {
    *this = ::std::move(from);
  }

  inline ObjectInfo& operator=(const ObjectInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectInfo& operator=(ObjectInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObjectInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObjectInfo* internal_default_instance() {
    return reinterpret_cast<const ObjectInfo*>(
               &_ObjectInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ObjectInfo& a, ObjectInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ObjectInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObjectInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ObjectInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ObjectInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ObjectInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ObjectInfo& from) {
    ObjectInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ObjectInfo";
  }
  protected:
  explicit ObjectInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPosInfoFieldNumber = 3,
    kStatInfoFieldNumber = 4,
    kPlayerInfoFieldNumber = 5,
    kObjectIdFieldNumber = 1,
    kObjectTypeFieldNumber = 2,
  };
  // .Protocol.PosInfo pos_info = 3;
  bool has_pos_info() const;
  private:
  bool _internal_has_pos_info() const;
  public:
  void clear_pos_info();
  const ::Protocol::PosInfo& pos_info() const;
  PROTOBUF_NODISCARD ::Protocol::PosInfo* release_pos_info();
  ::Protocol::PosInfo* mutable_pos_info();
  void set_allocated_pos_info(::Protocol::PosInfo* pos_info);
  private:
  const ::Protocol::PosInfo& _internal_pos_info() const;
  ::Protocol::PosInfo* _internal_mutable_pos_info();
  public:
  void unsafe_arena_set_allocated_pos_info(
      ::Protocol::PosInfo* pos_info);
  ::Protocol::PosInfo* unsafe_arena_release_pos_info();

  // .Protocol.StatInfo stat_info = 4;
  bool has_stat_info() const;
  private:
  bool _internal_has_stat_info() const;
  public:
  void clear_stat_info();
  const ::Protocol::StatInfo& stat_info() const;
  PROTOBUF_NODISCARD ::Protocol::StatInfo* release_stat_info();
  ::Protocol::StatInfo* mutable_stat_info();
  void set_allocated_stat_info(::Protocol::StatInfo* stat_info);
  private:
  const ::Protocol::StatInfo& _internal_stat_info() const;
  ::Protocol::StatInfo* _internal_mutable_stat_info();
  public:
  void unsafe_arena_set_allocated_stat_info(
      ::Protocol::StatInfo* stat_info);
  ::Protocol::StatInfo* unsafe_arena_release_stat_info();

  // optional .Protocol.PlayerInfo player_info = 5;
  bool has_player_info() const;
  private:
  bool _internal_has_player_info() const;
  public:
  void clear_player_info();
  const ::Protocol::PlayerInfo& player_info() const;
  PROTOBUF_NODISCARD ::Protocol::PlayerInfo* release_player_info();
  ::Protocol::PlayerInfo* mutable_player_info();
  void set_allocated_player_info(::Protocol::PlayerInfo* player_info);
  private:
  const ::Protocol::PlayerInfo& _internal_player_info() const;
  ::Protocol::PlayerInfo* _internal_mutable_player_info();
  public:
  void unsafe_arena_set_allocated_player_info(
      ::Protocol::PlayerInfo* player_info);
  ::Protocol::PlayerInfo* unsafe_arena_release_player_info();

  // uint64 object_id = 1;
  void clear_object_id();
  uint64_t object_id() const;
  void set_object_id(uint64_t value);
  private:
  uint64_t _internal_object_id() const;
  void _internal_set_object_id(uint64_t value);
  public:

  // .Protocol.ObjectType object_type = 2;
  void clear_object_type();
  ::Protocol::ObjectType object_type() const;
  void set_object_type(::Protocol::ObjectType value);
  private:
  ::Protocol::ObjectType _internal_object_type() const;
  void _internal_set_object_type(::Protocol::ObjectType value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ObjectInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::Protocol::PosInfo* pos_info_;
    ::Protocol::StatInfo* stat_info_;
    ::Protocol::PlayerInfo* player_info_;
    uint64_t object_id_;
    int object_type_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class PlayerInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.PlayerInfo) */ {
 public:
  inline PlayerInfo() : PlayerInfo(nullptr) {}
  ~PlayerInfo() override;
  explicit PROTOBUF_CONSTEXPR PlayerInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerInfo(const PlayerInfo& from);
  PlayerInfo(PlayerInfo&& from) noexcept
    : PlayerInfo() {
    *this = ::std::move(from);
  }

  inline PlayerInfo& operator=(const PlayerInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerInfo& operator=(PlayerInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerInfo* internal_default_instance() {
    return reinterpret_cast<const PlayerInfo*>(
               &_PlayerInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PlayerInfo& a, PlayerInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerInfo& from) {
    PlayerInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.PlayerInfo";
  }
  protected:
  explicit PlayerInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemsFieldNumber = 4,
    kEquipmentsFieldNumber = 5,
    kOverviewFieldNumber = 1,
    kGoldFieldNumber = 2,
    kExpFieldNumber = 3,
  };
  // repeated .Protocol.Item items = 4;
  int items_size() const;
  private:
  int _internal_items_size() const;
  public:
  void clear_items();
  ::Protocol::Item* mutable_items(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Item >*
      mutable_items();
  private:
  const ::Protocol::Item& _internal_items(int index) const;
  ::Protocol::Item* _internal_add_items();
  public:
  const ::Protocol::Item& items(int index) const;
  ::Protocol::Item* add_items();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Item >&
      items() const;

  // repeated .Protocol.Equipment Equipments = 5;
  int equipments_size() const;
  private:
  int _internal_equipments_size() const;
  public:
  void clear_equipments();
  ::Protocol::Equipment* mutable_equipments(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Equipment >*
      mutable_equipments();
  private:
  const ::Protocol::Equipment& _internal_equipments(int index) const;
  ::Protocol::Equipment* _internal_add_equipments();
  public:
  const ::Protocol::Equipment& equipments(int index) const;
  ::Protocol::Equipment* add_equipments();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Equipment >&
      equipments() const;

  // .Protocol.CharacterOverview overview = 1;
  bool has_overview() const;
  private:
  bool _internal_has_overview() const;
  public:
  void clear_overview();
  const ::Protocol::CharacterOverview& overview() const;
  PROTOBUF_NODISCARD ::Protocol::CharacterOverview* release_overview();
  ::Protocol::CharacterOverview* mutable_overview();
  void set_allocated_overview(::Protocol::CharacterOverview* overview);
  private:
  const ::Protocol::CharacterOverview& _internal_overview() const;
  ::Protocol::CharacterOverview* _internal_mutable_overview();
  public:
  void unsafe_arena_set_allocated_overview(
      ::Protocol::CharacterOverview* overview);
  ::Protocol::CharacterOverview* unsafe_arena_release_overview();

  // uint64 gold = 2;
  void clear_gold();
  uint64_t gold() const;
  void set_gold(uint64_t value);
  private:
  uint64_t _internal_gold() const;
  void _internal_set_gold(uint64_t value);
  public:

  // uint64 exp = 3;
  void clear_exp();
  uint64_t exp() const;
  void set_exp(uint64_t value);
  private:
  uint64_t _internal_exp() const;
  void _internal_set_exp(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.PlayerInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Item > items_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Equipment > equipments_;
    ::Protocol::CharacterOverview* overview_;
    uint64_t gold_;
    uint64_t exp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class PosInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.PosInfo) */ {
 public:
  inline PosInfo() : PosInfo(nullptr) {}
  ~PosInfo() override;
  explicit PROTOBUF_CONSTEXPR PosInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PosInfo(const PosInfo& from);
  PosInfo(PosInfo&& from) noexcept
    : PosInfo() {
    *this = ::std::move(from);
  }

  inline PosInfo& operator=(const PosInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PosInfo& operator=(PosInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PosInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const PosInfo* internal_default_instance() {
    return reinterpret_cast<const PosInfo*>(
               &_PosInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PosInfo& a, PosInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(PosInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PosInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PosInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PosInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PosInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PosInfo& from) {
    PosInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PosInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.PosInfo";
  }
  protected:
  explicit PosInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectIdFieldNumber = 1,
    kMapIdFieldNumber = 2,
    kXFieldNumber = 3,
    kYFieldNumber = 4,
    kZFieldNumber = 5,
    kYawFieldNumber = 6,
    kStateFieldNumber = 7,
  };
  // uint64 object_id = 1;
  void clear_object_id();
  uint64_t object_id() const;
  void set_object_id(uint64_t value);
  private:
  uint64_t _internal_object_id() const;
  void _internal_set_object_id(uint64_t value);
  public:

  // int32 map_id = 2;
  void clear_map_id();
  int32_t map_id() const;
  void set_map_id(int32_t value);
  private:
  int32_t _internal_map_id() const;
  void _internal_set_map_id(int32_t value);
  public:

  // float x = 3;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 4;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 5;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float yaw = 6;
  void clear_yaw();
  float yaw() const;
  void set_yaw(float value);
  private:
  float _internal_yaw() const;
  void _internal_set_yaw(float value);
  public:

  // .Protocol.MoveState state = 7;
  void clear_state();
  ::Protocol::MoveState state() const;
  void set_state(::Protocol::MoveState value);
  private:
  ::Protocol::MoveState _internal_state() const;
  void _internal_set_state(::Protocol::MoveState value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.PosInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t object_id_;
    int32_t map_id_;
    float x_;
    float y_;
    float z_;
    float yaw_;
    int state_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class StatInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.StatInfo) */ {
 public:
  inline StatInfo() : StatInfo(nullptr) {}
  ~StatInfo() override;
  explicit PROTOBUF_CONSTEXPR StatInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StatInfo(const StatInfo& from);
  StatInfo(StatInfo&& from) noexcept
    : StatInfo() {
    *this = ::std::move(from);
  }

  inline StatInfo& operator=(const StatInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline StatInfo& operator=(StatInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StatInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const StatInfo* internal_default_instance() {
    return reinterpret_cast<const StatInfo*>(
               &_StatInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(StatInfo& a, StatInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(StatInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StatInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StatInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StatInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StatInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StatInfo& from) {
    StatInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StatInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.StatInfo";
  }
  protected:
  explicit StatInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCurHpFieldNumber = 1,
    kMaxHpFieldNumber = 2,
    kCurMpFieldNumber = 3,
    kMaxMpFieldNumber = 4,
    kCurAttackFieldNumber = 5,
    kCurMagicFieldNumber = 6,
  };
  // int32 cur_hp = 1;
  void clear_cur_hp();
  int32_t cur_hp() const;
  void set_cur_hp(int32_t value);
  private:
  int32_t _internal_cur_hp() const;
  void _internal_set_cur_hp(int32_t value);
  public:

  // int32 max_hp = 2;
  void clear_max_hp();
  int32_t max_hp() const;
  void set_max_hp(int32_t value);
  private:
  int32_t _internal_max_hp() const;
  void _internal_set_max_hp(int32_t value);
  public:

  // int32 cur_mp = 3;
  void clear_cur_mp();
  int32_t cur_mp() const;
  void set_cur_mp(int32_t value);
  private:
  int32_t _internal_cur_mp() const;
  void _internal_set_cur_mp(int32_t value);
  public:

  // int32 max_mp = 4;
  void clear_max_mp();
  int32_t max_mp() const;
  void set_max_mp(int32_t value);
  private:
  int32_t _internal_max_mp() const;
  void _internal_set_max_mp(int32_t value);
  public:

  // int32 cur_attack = 5;
  void clear_cur_attack();
  int32_t cur_attack() const;
  void set_cur_attack(int32_t value);
  private:
  int32_t _internal_cur_attack() const;
  void _internal_set_cur_attack(int32_t value);
  public:

  // int32 cur_magic = 6;
  void clear_cur_magic();
  int32_t cur_magic() const;
  void set_cur_magic(int32_t value);
  private:
  int32_t _internal_cur_magic() const;
  void _internal_set_cur_magic(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.StatInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t cur_hp_;
    int32_t max_hp_;
    int32_t cur_mp_;
    int32_t max_mp_;
    int32_t cur_attack_;
    int32_t cur_magic_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class Item final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Item) */ {
 public:
  inline Item() : Item(nullptr) {}
  ~Item() override;
  explicit PROTOBUF_CONSTEXPR Item(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Item(const Item& from);
  Item(Item&& from) noexcept
    : Item() {
    *this = ::std::move(from);
  }

  inline Item& operator=(const Item& from) {
    CopyFrom(from);
    return *this;
  }
  inline Item& operator=(Item&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Item& default_instance() {
    return *internal_default_instance();
  }
  static inline const Item* internal_default_instance() {
    return reinterpret_cast<const Item*>(
               &_Item_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Item& a, Item& b) {
    a.Swap(&b);
  }
  inline void Swap(Item* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Item* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Item* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Item>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Item& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Item& from) {
    Item::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Item* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Item";
  }
  protected:
  explicit Item(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTemplateIdFieldNumber = 1,
    kSlotIdFieldNumber = 2,
    kCountFieldNumber = 3,
  };
  // int32 template_id = 1;
  void clear_template_id();
  int32_t template_id() const;
  void set_template_id(int32_t value);
  private:
  int32_t _internal_template_id() const;
  void _internal_set_template_id(int32_t value);
  public:

  // int32 slot_id = 2;
  void clear_slot_id();
  int32_t slot_id() const;
  void set_slot_id(int32_t value);
  private:
  int32_t _internal_slot_id() const;
  void _internal_set_slot_id(int32_t value);
  public:

  // int32 count = 3;
  void clear_count();
  int32_t count() const;
  void set_count(int32_t value);
  private:
  int32_t _internal_count() const;
  void _internal_set_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Item)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t template_id_;
    int32_t slot_id_;
    int32_t count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class Equipment final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Equipment) */ {
 public:
  inline Equipment() : Equipment(nullptr) {}
  ~Equipment() override;
  explicit PROTOBUF_CONSTEXPR Equipment(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Equipment(const Equipment& from);
  Equipment(Equipment&& from) noexcept
    : Equipment() {
    *this = ::std::move(from);
  }

  inline Equipment& operator=(const Equipment& from) {
    CopyFrom(from);
    return *this;
  }
  inline Equipment& operator=(Equipment&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Equipment& default_instance() {
    return *internal_default_instance();
  }
  static inline const Equipment* internal_default_instance() {
    return reinterpret_cast<const Equipment*>(
               &_Equipment_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Equipment& a, Equipment& b) {
    a.Swap(&b);
  }
  inline void Swap(Equipment* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Equipment* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Equipment* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Equipment>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Equipment& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Equipment& from) {
    Equipment::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Equipment* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Equipment";
  }
  protected:
  explicit Equipment(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemUidFieldNumber = 1,
    kTemplateIdFieldNumber = 2,
    kSlotIdFieldNumber = 3,
    kCountFieldNumber = 4,
  };
  // int32 item_uid = 1;
  void clear_item_uid();
  int32_t item_uid() const;
  void set_item_uid(int32_t value);
  private:
  int32_t _internal_item_uid() const;
  void _internal_set_item_uid(int32_t value);
  public:

  // int32 template_id = 2;
  void clear_template_id();
  int32_t template_id() const;
  void set_template_id(int32_t value);
  private:
  int32_t _internal_template_id() const;
  void _internal_set_template_id(int32_t value);
  public:

  // int32 slot_id = 3;
  void clear_slot_id();
  int32_t slot_id() const;
  void set_slot_id(int32_t value);
  private:
  int32_t _internal_slot_id() const;
  void _internal_set_slot_id(int32_t value);
  public:

  // int32 count = 4;
  void clear_count();
  int32_t count() const;
  void set_count(int32_t value);
  private:
  int32_t _internal_count() const;
  void _internal_set_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Equipment)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t item_uid_;
    int32_t template_id_;
    int32_t slot_id_;
    int32_t count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class Effect final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Effect) */ {
 public:
  inline Effect() : Effect(nullptr) {}
  ~Effect() override;
  explicit PROTOBUF_CONSTEXPR Effect(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Effect(const Effect& from);
  Effect(Effect&& from) noexcept
    : Effect() {
    *this = ::std::move(from);
  }

  inline Effect& operator=(const Effect& from) {
    CopyFrom(from);
    return *this;
  }
  inline Effect& operator=(Effect&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Effect& default_instance() {
    return *internal_default_instance();
  }
  static inline const Effect* internal_default_instance() {
    return reinterpret_cast<const Effect*>(
               &_Effect_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(Effect& a, Effect& b) {
    a.Swap(&b);
  }
  inline void Swap(Effect* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Effect* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Effect* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Effect>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Effect& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Effect& from) {
    Effect::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Effect* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Effect";
  }
  protected:
  explicit Effect(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEffectIdFieldNumber = 1,
    kDurationFieldNumber = 2,
  };
  // int32 effect_id = 1;
  void clear_effect_id();
  int32_t effect_id() const;
  void set_effect_id(int32_t value);
  private:
  int32_t _internal_effect_id() const;
  void _internal_set_effect_id(int32_t value);
  public:

  // float duration = 2;
  void clear_duration();
  float duration() const;
  void set_duration(float value);
  private:
  float _internal_duration() const;
  void _internal_set_duration(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Effect)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t effect_id_;
    float duration_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CharacterOverview

// uint64 character_id = 1;
inline void CharacterOverview::clear_character_id() {
  _impl_.character_id_ = uint64_t{0u};
}
inline uint64_t CharacterOverview::_internal_character_id() const {
  return _impl_.character_id_;
}
inline uint64_t CharacterOverview::character_id() const {
  // @@protoc_insertion_point(field_get:Protocol.CharacterOverview.character_id)
  return _internal_character_id();
}
inline void CharacterOverview::_internal_set_character_id(uint64_t value) {
  
  _impl_.character_id_ = value;
}
inline void CharacterOverview::set_character_id(uint64_t value) {
  _internal_set_character_id(value);
  // @@protoc_insertion_point(field_set:Protocol.CharacterOverview.character_id)
}

// .Protocol.CharacterClass class = 2;
inline void CharacterOverview::clear_class_() {
  _impl_.class__ = 0;
}
inline ::Protocol::CharacterClass CharacterOverview::_internal_class_() const {
  return static_cast< ::Protocol::CharacterClass >(_impl_.class__);
}
inline ::Protocol::CharacterClass CharacterOverview::class_() const {
  // @@protoc_insertion_point(field_get:Protocol.CharacterOverview.class)
  return _internal_class_();
}
inline void CharacterOverview::_internal_set_class_(::Protocol::CharacterClass value) {
  
  _impl_.class__ = value;
}
inline void CharacterOverview::set_class_(::Protocol::CharacterClass value) {
  _internal_set_class_(value);
  // @@protoc_insertion_point(field_set:Protocol.CharacterOverview.class)
}

// string name = 3;
inline void CharacterOverview::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& CharacterOverview::name() const {
  // @@protoc_insertion_point(field_get:Protocol.CharacterOverview.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CharacterOverview::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.CharacterOverview.name)
}
inline std::string* CharacterOverview::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Protocol.CharacterOverview.name)
  return _s;
}
inline const std::string& CharacterOverview::_internal_name() const {
  return _impl_.name_.Get();
}
inline void CharacterOverview::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* CharacterOverview::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* CharacterOverview::release_name() {
  // @@protoc_insertion_point(field_release:Protocol.CharacterOverview.name)
  return _impl_.name_.Release();
}
inline void CharacterOverview::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.CharacterOverview.name)
}

// uint32 level = 4;
inline void CharacterOverview::clear_level() {
  _impl_.level_ = 0u;
}
inline uint32_t CharacterOverview::_internal_level() const {
  return _impl_.level_;
}
inline uint32_t CharacterOverview::level() const {
  // @@protoc_insertion_point(field_get:Protocol.CharacterOverview.level)
  return _internal_level();
}
inline void CharacterOverview::_internal_set_level(uint32_t value) {
  
  _impl_.level_ = value;
}
inline void CharacterOverview::set_level(uint32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:Protocol.CharacterOverview.level)
}

// -------------------------------------------------------------------

// ObjectInfo

// uint64 object_id = 1;
inline void ObjectInfo::clear_object_id() {
  _impl_.object_id_ = uint64_t{0u};
}
inline uint64_t ObjectInfo::_internal_object_id() const {
  return _impl_.object_id_;
}
inline uint64_t ObjectInfo::object_id() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.object_id)
  return _internal_object_id();
}
inline void ObjectInfo::_internal_set_object_id(uint64_t value) {
  
  _impl_.object_id_ = value;
}
inline void ObjectInfo::set_object_id(uint64_t value) {
  _internal_set_object_id(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.object_id)
}

// .Protocol.ObjectType object_type = 2;
inline void ObjectInfo::clear_object_type() {
  _impl_.object_type_ = 0;
}
inline ::Protocol::ObjectType ObjectInfo::_internal_object_type() const {
  return static_cast< ::Protocol::ObjectType >(_impl_.object_type_);
}
inline ::Protocol::ObjectType ObjectInfo::object_type() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.object_type)
  return _internal_object_type();
}
inline void ObjectInfo::_internal_set_object_type(::Protocol::ObjectType value) {
  
  _impl_.object_type_ = value;
}
inline void ObjectInfo::set_object_type(::Protocol::ObjectType value) {
  _internal_set_object_type(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.object_type)
}

// .Protocol.PosInfo pos_info = 3;
inline bool ObjectInfo::_internal_has_pos_info() const {
  return this != internal_default_instance() && _impl_.pos_info_ != nullptr;
}
inline bool ObjectInfo::has_pos_info() const {
  return _internal_has_pos_info();
}
inline void ObjectInfo::clear_pos_info() {
  if (GetArenaForAllocation() == nullptr && _impl_.pos_info_ != nullptr) {
    delete _impl_.pos_info_;
  }
  _impl_.pos_info_ = nullptr;
}
inline const ::Protocol::PosInfo& ObjectInfo::_internal_pos_info() const {
  const ::Protocol::PosInfo* p = _impl_.pos_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::PosInfo&>(
      ::Protocol::_PosInfo_default_instance_);
}
inline const ::Protocol::PosInfo& ObjectInfo::pos_info() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.pos_info)
  return _internal_pos_info();
}
inline void ObjectInfo::unsafe_arena_set_allocated_pos_info(
    ::Protocol::PosInfo* pos_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.pos_info_);
  }
  _impl_.pos_info_ = pos_info;
  if (pos_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.ObjectInfo.pos_info)
}
inline ::Protocol::PosInfo* ObjectInfo::release_pos_info() {
  
  ::Protocol::PosInfo* temp = _impl_.pos_info_;
  _impl_.pos_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::PosInfo* ObjectInfo::unsafe_arena_release_pos_info() {
  // @@protoc_insertion_point(field_release:Protocol.ObjectInfo.pos_info)
  
  ::Protocol::PosInfo* temp = _impl_.pos_info_;
  _impl_.pos_info_ = nullptr;
  return temp;
}
inline ::Protocol::PosInfo* ObjectInfo::_internal_mutable_pos_info() {
  
  if (_impl_.pos_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::PosInfo>(GetArenaForAllocation());
    _impl_.pos_info_ = p;
  }
  return _impl_.pos_info_;
}
inline ::Protocol::PosInfo* ObjectInfo::mutable_pos_info() {
  ::Protocol::PosInfo* _msg = _internal_mutable_pos_info();
  // @@protoc_insertion_point(field_mutable:Protocol.ObjectInfo.pos_info)
  return _msg;
}
inline void ObjectInfo::set_allocated_pos_info(::Protocol::PosInfo* pos_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.pos_info_;
  }
  if (pos_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(pos_info);
    if (message_arena != submessage_arena) {
      pos_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pos_info, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.pos_info_ = pos_info;
  // @@protoc_insertion_point(field_set_allocated:Protocol.ObjectInfo.pos_info)
}

// .Protocol.StatInfo stat_info = 4;
inline bool ObjectInfo::_internal_has_stat_info() const {
  return this != internal_default_instance() && _impl_.stat_info_ != nullptr;
}
inline bool ObjectInfo::has_stat_info() const {
  return _internal_has_stat_info();
}
inline void ObjectInfo::clear_stat_info() {
  if (GetArenaForAllocation() == nullptr && _impl_.stat_info_ != nullptr) {
    delete _impl_.stat_info_;
  }
  _impl_.stat_info_ = nullptr;
}
inline const ::Protocol::StatInfo& ObjectInfo::_internal_stat_info() const {
  const ::Protocol::StatInfo* p = _impl_.stat_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::StatInfo&>(
      ::Protocol::_StatInfo_default_instance_);
}
inline const ::Protocol::StatInfo& ObjectInfo::stat_info() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.stat_info)
  return _internal_stat_info();
}
inline void ObjectInfo::unsafe_arena_set_allocated_stat_info(
    ::Protocol::StatInfo* stat_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.stat_info_);
  }
  _impl_.stat_info_ = stat_info;
  if (stat_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.ObjectInfo.stat_info)
}
inline ::Protocol::StatInfo* ObjectInfo::release_stat_info() {
  
  ::Protocol::StatInfo* temp = _impl_.stat_info_;
  _impl_.stat_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::StatInfo* ObjectInfo::unsafe_arena_release_stat_info() {
  // @@protoc_insertion_point(field_release:Protocol.ObjectInfo.stat_info)
  
  ::Protocol::StatInfo* temp = _impl_.stat_info_;
  _impl_.stat_info_ = nullptr;
  return temp;
}
inline ::Protocol::StatInfo* ObjectInfo::_internal_mutable_stat_info() {
  
  if (_impl_.stat_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::StatInfo>(GetArenaForAllocation());
    _impl_.stat_info_ = p;
  }
  return _impl_.stat_info_;
}
inline ::Protocol::StatInfo* ObjectInfo::mutable_stat_info() {
  ::Protocol::StatInfo* _msg = _internal_mutable_stat_info();
  // @@protoc_insertion_point(field_mutable:Protocol.ObjectInfo.stat_info)
  return _msg;
}
inline void ObjectInfo::set_allocated_stat_info(::Protocol::StatInfo* stat_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.stat_info_;
  }
  if (stat_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(stat_info);
    if (message_arena != submessage_arena) {
      stat_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stat_info, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.stat_info_ = stat_info;
  // @@protoc_insertion_point(field_set_allocated:Protocol.ObjectInfo.stat_info)
}

// optional .Protocol.PlayerInfo player_info = 5;
inline bool ObjectInfo::_internal_has_player_info() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.player_info_ != nullptr);
  return value;
}
inline bool ObjectInfo::has_player_info() const {
  return _internal_has_player_info();
}
inline void ObjectInfo::clear_player_info() {
  if (_impl_.player_info_ != nullptr) _impl_.player_info_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::Protocol::PlayerInfo& ObjectInfo::_internal_player_info() const {
  const ::Protocol::PlayerInfo* p = _impl_.player_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::PlayerInfo&>(
      ::Protocol::_PlayerInfo_default_instance_);
}
inline const ::Protocol::PlayerInfo& ObjectInfo::player_info() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.player_info)
  return _internal_player_info();
}
inline void ObjectInfo::unsafe_arena_set_allocated_player_info(
    ::Protocol::PlayerInfo* player_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.player_info_);
  }
  _impl_.player_info_ = player_info;
  if (player_info) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.ObjectInfo.player_info)
}
inline ::Protocol::PlayerInfo* ObjectInfo::release_player_info() {
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::PlayerInfo* temp = _impl_.player_info_;
  _impl_.player_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::PlayerInfo* ObjectInfo::unsafe_arena_release_player_info() {
  // @@protoc_insertion_point(field_release:Protocol.ObjectInfo.player_info)
  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::PlayerInfo* temp = _impl_.player_info_;
  _impl_.player_info_ = nullptr;
  return temp;
}
inline ::Protocol::PlayerInfo* ObjectInfo::_internal_mutable_player_info() {
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.player_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::PlayerInfo>(GetArenaForAllocation());
    _impl_.player_info_ = p;
  }
  return _impl_.player_info_;
}
inline ::Protocol::PlayerInfo* ObjectInfo::mutable_player_info() {
  ::Protocol::PlayerInfo* _msg = _internal_mutable_player_info();
  // @@protoc_insertion_point(field_mutable:Protocol.ObjectInfo.player_info)
  return _msg;
}
inline void ObjectInfo::set_allocated_player_info(::Protocol::PlayerInfo* player_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.player_info_;
  }
  if (player_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(player_info);
    if (message_arena != submessage_arena) {
      player_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, player_info, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.player_info_ = player_info;
  // @@protoc_insertion_point(field_set_allocated:Protocol.ObjectInfo.player_info)
}

// -------------------------------------------------------------------

// PlayerInfo

// .Protocol.CharacterOverview overview = 1;
inline bool PlayerInfo::_internal_has_overview() const {
  return this != internal_default_instance() && _impl_.overview_ != nullptr;
}
inline bool PlayerInfo::has_overview() const {
  return _internal_has_overview();
}
inline void PlayerInfo::clear_overview() {
  if (GetArenaForAllocation() == nullptr && _impl_.overview_ != nullptr) {
    delete _impl_.overview_;
  }
  _impl_.overview_ = nullptr;
}
inline const ::Protocol::CharacterOverview& PlayerInfo::_internal_overview() const {
  const ::Protocol::CharacterOverview* p = _impl_.overview_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::CharacterOverview&>(
      ::Protocol::_CharacterOverview_default_instance_);
}
inline const ::Protocol::CharacterOverview& PlayerInfo::overview() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.overview)
  return _internal_overview();
}
inline void PlayerInfo::unsafe_arena_set_allocated_overview(
    ::Protocol::CharacterOverview* overview) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.overview_);
  }
  _impl_.overview_ = overview;
  if (overview) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.PlayerInfo.overview)
}
inline ::Protocol::CharacterOverview* PlayerInfo::release_overview() {
  
  ::Protocol::CharacterOverview* temp = _impl_.overview_;
  _impl_.overview_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::CharacterOverview* PlayerInfo::unsafe_arena_release_overview() {
  // @@protoc_insertion_point(field_release:Protocol.PlayerInfo.overview)
  
  ::Protocol::CharacterOverview* temp = _impl_.overview_;
  _impl_.overview_ = nullptr;
  return temp;
}
inline ::Protocol::CharacterOverview* PlayerInfo::_internal_mutable_overview() {
  
  if (_impl_.overview_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::CharacterOverview>(GetArenaForAllocation());
    _impl_.overview_ = p;
  }
  return _impl_.overview_;
}
inline ::Protocol::CharacterOverview* PlayerInfo::mutable_overview() {
  ::Protocol::CharacterOverview* _msg = _internal_mutable_overview();
  // @@protoc_insertion_point(field_mutable:Protocol.PlayerInfo.overview)
  return _msg;
}
inline void PlayerInfo::set_allocated_overview(::Protocol::CharacterOverview* overview) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.overview_;
  }
  if (overview) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(overview);
    if (message_arena != submessage_arena) {
      overview = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, overview, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.overview_ = overview;
  // @@protoc_insertion_point(field_set_allocated:Protocol.PlayerInfo.overview)
}

// uint64 gold = 2;
inline void PlayerInfo::clear_gold() {
  _impl_.gold_ = uint64_t{0u};
}
inline uint64_t PlayerInfo::_internal_gold() const {
  return _impl_.gold_;
}
inline uint64_t PlayerInfo::gold() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.gold)
  return _internal_gold();
}
inline void PlayerInfo::_internal_set_gold(uint64_t value) {
  
  _impl_.gold_ = value;
}
inline void PlayerInfo::set_gold(uint64_t value) {
  _internal_set_gold(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.gold)
}

// uint64 exp = 3;
inline void PlayerInfo::clear_exp() {
  _impl_.exp_ = uint64_t{0u};
}
inline uint64_t PlayerInfo::_internal_exp() const {
  return _impl_.exp_;
}
inline uint64_t PlayerInfo::exp() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.exp)
  return _internal_exp();
}
inline void PlayerInfo::_internal_set_exp(uint64_t value) {
  
  _impl_.exp_ = value;
}
inline void PlayerInfo::set_exp(uint64_t value) {
  _internal_set_exp(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.exp)
}

// repeated .Protocol.Item items = 4;
inline int PlayerInfo::_internal_items_size() const {
  return _impl_.items_.size();
}
inline int PlayerInfo::items_size() const {
  return _internal_items_size();
}
inline void PlayerInfo::clear_items() {
  _impl_.items_.Clear();
}
inline ::Protocol::Item* PlayerInfo::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.PlayerInfo.items)
  return _impl_.items_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Item >*
PlayerInfo::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.PlayerInfo.items)
  return &_impl_.items_;
}
inline const ::Protocol::Item& PlayerInfo::_internal_items(int index) const {
  return _impl_.items_.Get(index);
}
inline const ::Protocol::Item& PlayerInfo::items(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.items)
  return _internal_items(index);
}
inline ::Protocol::Item* PlayerInfo::_internal_add_items() {
  return _impl_.items_.Add();
}
inline ::Protocol::Item* PlayerInfo::add_items() {
  ::Protocol::Item* _add = _internal_add_items();
  // @@protoc_insertion_point(field_add:Protocol.PlayerInfo.items)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Item >&
PlayerInfo::items() const {
  // @@protoc_insertion_point(field_list:Protocol.PlayerInfo.items)
  return _impl_.items_;
}

// repeated .Protocol.Equipment Equipments = 5;
inline int PlayerInfo::_internal_equipments_size() const {
  return _impl_.equipments_.size();
}
inline int PlayerInfo::equipments_size() const {
  return _internal_equipments_size();
}
inline void PlayerInfo::clear_equipments() {
  _impl_.equipments_.Clear();
}
inline ::Protocol::Equipment* PlayerInfo::mutable_equipments(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.PlayerInfo.Equipments)
  return _impl_.equipments_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Equipment >*
PlayerInfo::mutable_equipments() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.PlayerInfo.Equipments)
  return &_impl_.equipments_;
}
inline const ::Protocol::Equipment& PlayerInfo::_internal_equipments(int index) const {
  return _impl_.equipments_.Get(index);
}
inline const ::Protocol::Equipment& PlayerInfo::equipments(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.Equipments)
  return _internal_equipments(index);
}
inline ::Protocol::Equipment* PlayerInfo::_internal_add_equipments() {
  return _impl_.equipments_.Add();
}
inline ::Protocol::Equipment* PlayerInfo::add_equipments() {
  ::Protocol::Equipment* _add = _internal_add_equipments();
  // @@protoc_insertion_point(field_add:Protocol.PlayerInfo.Equipments)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::Equipment >&
PlayerInfo::equipments() const {
  // @@protoc_insertion_point(field_list:Protocol.PlayerInfo.Equipments)
  return _impl_.equipments_;
}

// -------------------------------------------------------------------

// PosInfo

// uint64 object_id = 1;
inline void PosInfo::clear_object_id() {
  _impl_.object_id_ = uint64_t{0u};
}
inline uint64_t PosInfo::_internal_object_id() const {
  return _impl_.object_id_;
}
inline uint64_t PosInfo::object_id() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.object_id)
  return _internal_object_id();
}
inline void PosInfo::_internal_set_object_id(uint64_t value) {
  
  _impl_.object_id_ = value;
}
inline void PosInfo::set_object_id(uint64_t value) {
  _internal_set_object_id(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.object_id)
}

// int32 map_id = 2;
inline void PosInfo::clear_map_id() {
  _impl_.map_id_ = 0;
}
inline int32_t PosInfo::_internal_map_id() const {
  return _impl_.map_id_;
}
inline int32_t PosInfo::map_id() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.map_id)
  return _internal_map_id();
}
inline void PosInfo::_internal_set_map_id(int32_t value) {
  
  _impl_.map_id_ = value;
}
inline void PosInfo::set_map_id(int32_t value) {
  _internal_set_map_id(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.map_id)
}

// float x = 3;
inline void PosInfo::clear_x() {
  _impl_.x_ = 0;
}
inline float PosInfo::_internal_x() const {
  return _impl_.x_;
}
inline float PosInfo::x() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.x)
  return _internal_x();
}
inline void PosInfo::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void PosInfo::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.x)
}

// float y = 4;
inline void PosInfo::clear_y() {
  _impl_.y_ = 0;
}
inline float PosInfo::_internal_y() const {
  return _impl_.y_;
}
inline float PosInfo::y() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.y)
  return _internal_y();
}
inline void PosInfo::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void PosInfo::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.y)
}

// float z = 5;
inline void PosInfo::clear_z() {
  _impl_.z_ = 0;
}
inline float PosInfo::_internal_z() const {
  return _impl_.z_;
}
inline float PosInfo::z() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.z)
  return _internal_z();
}
inline void PosInfo::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void PosInfo::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.z)
}

// float yaw = 6;
inline void PosInfo::clear_yaw() {
  _impl_.yaw_ = 0;
}
inline float PosInfo::_internal_yaw() const {
  return _impl_.yaw_;
}
inline float PosInfo::yaw() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.yaw)
  return _internal_yaw();
}
inline void PosInfo::_internal_set_yaw(float value) {
  
  _impl_.yaw_ = value;
}
inline void PosInfo::set_yaw(float value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.yaw)
}

// .Protocol.MoveState state = 7;
inline void PosInfo::clear_state() {
  _impl_.state_ = 0;
}
inline ::Protocol::MoveState PosInfo::_internal_state() const {
  return static_cast< ::Protocol::MoveState >(_impl_.state_);
}
inline ::Protocol::MoveState PosInfo::state() const {
  // @@protoc_insertion_point(field_get:Protocol.PosInfo.state)
  return _internal_state();
}
inline void PosInfo::_internal_set_state(::Protocol::MoveState value) {
  
  _impl_.state_ = value;
}
inline void PosInfo::set_state(::Protocol::MoveState value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:Protocol.PosInfo.state)
}

// -------------------------------------------------------------------

// StatInfo

// int32 cur_hp = 1;
inline void StatInfo::clear_cur_hp() {
  _impl_.cur_hp_ = 0;
}
inline int32_t StatInfo::_internal_cur_hp() const {
  return _impl_.cur_hp_;
}
inline int32_t StatInfo::cur_hp() const {
  // @@protoc_insertion_point(field_get:Protocol.StatInfo.cur_hp)
  return _internal_cur_hp();
}
inline void StatInfo::_internal_set_cur_hp(int32_t value) {
  
  _impl_.cur_hp_ = value;
}
inline void StatInfo::set_cur_hp(int32_t value) {
  _internal_set_cur_hp(value);
  // @@protoc_insertion_point(field_set:Protocol.StatInfo.cur_hp)
}

// int32 max_hp = 2;
inline void StatInfo::clear_max_hp() {
  _impl_.max_hp_ = 0;
}
inline int32_t StatInfo::_internal_max_hp() const {
  return _impl_.max_hp_;
}
inline int32_t StatInfo::max_hp() const {
  // @@protoc_insertion_point(field_get:Protocol.StatInfo.max_hp)
  return _internal_max_hp();
}
inline void StatInfo::_internal_set_max_hp(int32_t value) {
  
  _impl_.max_hp_ = value;
}
inline void StatInfo::set_max_hp(int32_t value) {
  _internal_set_max_hp(value);
  // @@protoc_insertion_point(field_set:Protocol.StatInfo.max_hp)
}

// int32 cur_mp = 3;
inline void StatInfo::clear_cur_mp() {
  _impl_.cur_mp_ = 0;
}
inline int32_t StatInfo::_internal_cur_mp() const {
  return _impl_.cur_mp_;
}
inline int32_t StatInfo::cur_mp() const {
  // @@protoc_insertion_point(field_get:Protocol.StatInfo.cur_mp)
  return _internal_cur_mp();
}
inline void StatInfo::_internal_set_cur_mp(int32_t value) {
  
  _impl_.cur_mp_ = value;
}
inline void StatInfo::set_cur_mp(int32_t value) {
  _internal_set_cur_mp(value);
  // @@protoc_insertion_point(field_set:Protocol.StatInfo.cur_mp)
}

// int32 max_mp = 4;
inline void StatInfo::clear_max_mp() {
  _impl_.max_mp_ = 0;
}
inline int32_t StatInfo::_internal_max_mp() const {
  return _impl_.max_mp_;
}
inline int32_t StatInfo::max_mp() const {
  // @@protoc_insertion_point(field_get:Protocol.StatInfo.max_mp)
  return _internal_max_mp();
}
inline void StatInfo::_internal_set_max_mp(int32_t value) {
  
  _impl_.max_mp_ = value;
}
inline void StatInfo::set_max_mp(int32_t value) {
  _internal_set_max_mp(value);
  // @@protoc_insertion_point(field_set:Protocol.StatInfo.max_mp)
}

// int32 cur_attack = 5;
inline void StatInfo::clear_cur_attack() {
  _impl_.cur_attack_ = 0;
}
inline int32_t StatInfo::_internal_cur_attack() const {
  return _impl_.cur_attack_;
}
inline int32_t StatInfo::cur_attack() const {
  // @@protoc_insertion_point(field_get:Protocol.StatInfo.cur_attack)
  return _internal_cur_attack();
}
inline void StatInfo::_internal_set_cur_attack(int32_t value) {
  
  _impl_.cur_attack_ = value;
}
inline void StatInfo::set_cur_attack(int32_t value) {
  _internal_set_cur_attack(value);
  // @@protoc_insertion_point(field_set:Protocol.StatInfo.cur_attack)
}

// int32 cur_magic = 6;
inline void StatInfo::clear_cur_magic() {
  _impl_.cur_magic_ = 0;
}
inline int32_t StatInfo::_internal_cur_magic() const {
  return _impl_.cur_magic_;
}
inline int32_t StatInfo::cur_magic() const {
  // @@protoc_insertion_point(field_get:Protocol.StatInfo.cur_magic)
  return _internal_cur_magic();
}
inline void StatInfo::_internal_set_cur_magic(int32_t value) {
  
  _impl_.cur_magic_ = value;
}
inline void StatInfo::set_cur_magic(int32_t value) {
  _internal_set_cur_magic(value);
  // @@protoc_insertion_point(field_set:Protocol.StatInfo.cur_magic)
}

// -------------------------------------------------------------------

// Item

// int32 template_id = 1;
inline void Item::clear_template_id() {
  _impl_.template_id_ = 0;
}
inline int32_t Item::_internal_template_id() const {
  return _impl_.template_id_;
}
inline int32_t Item::template_id() const {
  // @@protoc_insertion_point(field_get:Protocol.Item.template_id)
  return _internal_template_id();
}
inline void Item::_internal_set_template_id(int32_t value) {
  
  _impl_.template_id_ = value;
}
inline void Item::set_template_id(int32_t value) {
  _internal_set_template_id(value);
  // @@protoc_insertion_point(field_set:Protocol.Item.template_id)
}

// int32 slot_id = 2;
inline void Item::clear_slot_id() {
  _impl_.slot_id_ = 0;
}
inline int32_t Item::_internal_slot_id() const {
  return _impl_.slot_id_;
}
inline int32_t Item::slot_id() const {
  // @@protoc_insertion_point(field_get:Protocol.Item.slot_id)
  return _internal_slot_id();
}
inline void Item::_internal_set_slot_id(int32_t value) {
  
  _impl_.slot_id_ = value;
}
inline void Item::set_slot_id(int32_t value) {
  _internal_set_slot_id(value);
  // @@protoc_insertion_point(field_set:Protocol.Item.slot_id)
}

// int32 count = 3;
inline void Item::clear_count() {
  _impl_.count_ = 0;
}
inline int32_t Item::_internal_count() const {
  return _impl_.count_;
}
inline int32_t Item::count() const {
  // @@protoc_insertion_point(field_get:Protocol.Item.count)
  return _internal_count();
}
inline void Item::_internal_set_count(int32_t value) {
  
  _impl_.count_ = value;
}
inline void Item::set_count(int32_t value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:Protocol.Item.count)
}

// -------------------------------------------------------------------

// Equipment

// int32 item_uid = 1;
inline void Equipment::clear_item_uid() {
  _impl_.item_uid_ = 0;
}
inline int32_t Equipment::_internal_item_uid() const {
  return _impl_.item_uid_;
}
inline int32_t Equipment::item_uid() const {
  // @@protoc_insertion_point(field_get:Protocol.Equipment.item_uid)
  return _internal_item_uid();
}
inline void Equipment::_internal_set_item_uid(int32_t value) {
  
  _impl_.item_uid_ = value;
}
inline void Equipment::set_item_uid(int32_t value) {
  _internal_set_item_uid(value);
  // @@protoc_insertion_point(field_set:Protocol.Equipment.item_uid)
}

// int32 template_id = 2;
inline void Equipment::clear_template_id() {
  _impl_.template_id_ = 0;
}
inline int32_t Equipment::_internal_template_id() const {
  return _impl_.template_id_;
}
inline int32_t Equipment::template_id() const {
  // @@protoc_insertion_point(field_get:Protocol.Equipment.template_id)
  return _internal_template_id();
}
inline void Equipment::_internal_set_template_id(int32_t value) {
  
  _impl_.template_id_ = value;
}
inline void Equipment::set_template_id(int32_t value) {
  _internal_set_template_id(value);
  // @@protoc_insertion_point(field_set:Protocol.Equipment.template_id)
}

// int32 slot_id = 3;
inline void Equipment::clear_slot_id() {
  _impl_.slot_id_ = 0;
}
inline int32_t Equipment::_internal_slot_id() const {
  return _impl_.slot_id_;
}
inline int32_t Equipment::slot_id() const {
  // @@protoc_insertion_point(field_get:Protocol.Equipment.slot_id)
  return _internal_slot_id();
}
inline void Equipment::_internal_set_slot_id(int32_t value) {
  
  _impl_.slot_id_ = value;
}
inline void Equipment::set_slot_id(int32_t value) {
  _internal_set_slot_id(value);
  // @@protoc_insertion_point(field_set:Protocol.Equipment.slot_id)
}

// int32 count = 4;
inline void Equipment::clear_count() {
  _impl_.count_ = 0;
}
inline int32_t Equipment::_internal_count() const {
  return _impl_.count_;
}
inline int32_t Equipment::count() const {
  // @@protoc_insertion_point(field_get:Protocol.Equipment.count)
  return _internal_count();
}
inline void Equipment::_internal_set_count(int32_t value) {
  
  _impl_.count_ = value;
}
inline void Equipment::set_count(int32_t value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:Protocol.Equipment.count)
}

// -------------------------------------------------------------------

// Effect

// int32 effect_id = 1;
inline void Effect::clear_effect_id() {
  _impl_.effect_id_ = 0;
}
inline int32_t Effect::_internal_effect_id() const {
  return _impl_.effect_id_;
}
inline int32_t Effect::effect_id() const {
  // @@protoc_insertion_point(field_get:Protocol.Effect.effect_id)
  return _internal_effect_id();
}
inline void Effect::_internal_set_effect_id(int32_t value) {
  
  _impl_.effect_id_ = value;
}
inline void Effect::set_effect_id(int32_t value) {
  _internal_set_effect_id(value);
  // @@protoc_insertion_point(field_set:Protocol.Effect.effect_id)
}

// float duration = 2;
inline void Effect::clear_duration() {
  _impl_.duration_ = 0;
}
inline float Effect::_internal_duration() const {
  return _impl_.duration_;
}
inline float Effect::duration() const {
  // @@protoc_insertion_point(field_get:Protocol.Effect.duration)
  return _internal_duration();
}
inline void Effect::_internal_set_duration(float value) {
  
  _impl_.duration_ = value;
}
inline void Effect::set_duration(float value) {
  _internal_set_duration(value);
  // @@protoc_insertion_point(field_set:Protocol.Effect.duration)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
